stages:
  - build
  - test

default:
  image: openjdk:15
  before_script:
    - chmod +x gradlew
  tags:
    - docker

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew check
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' build/reports/jacoco/test/jacocoTestReport.csv
  artifacts:
    paths:
      - build/reports/jacoco/test
    reports:
      junit:
        - build/test-results/test/**/TEST-*.xml
